# Generated by Django 4.1.5 on 2023-02-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_shop', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
